### ISSUE TITLE
无法通过滑动验证码

### ISSUE THREAD

**Issue by ymy2078069948** [murphys7017/polaris-qq-chat-bot#3]
https://user-images.githubusercontent.com/103635982/203739622-92eb8a94-4209-42d0-ac52-698d23830926.mp4

不知道该怎么办了，不是闪退，
![image](https://user-images.githubusercontent.com/103635982/203740420-e212b923-67cf-4130-a079-1dc026ed0f0f.png)

**Comment by murphys7017** [comment]
在启动设备上登录qq或者tim之后再试一下

Yuki’s

发件人: ***@***.***>
发送时间: 2022年11月24日 17:04
收件人: ***@***.***>
抄送: ***@***.***>
主题: [murphys7017/polaris-qq-chat-bot] 无法通过滑动验证码 (Issue #3)


https://user-images.githubusercontent.com/103635982/203739622-92eb8a94-4209-42d0-ac52-698d23830926.mp4

不知道该怎么办了，不是闪退，
[image]<https://user-images.githubusercontent.com/103635982/203740420-e212b923-67cf-4130-a079-1dc026ed0f0f.png>

―

**Comment by ymy2078069948** [comment]
登录QQ了，也闪退

**Comment by murphys7017** [comment]
我的问题，没有看你发的视频，根据报错截图判断了
TxCaptchaHelper是一个手机的辅助验证软件，用于完成qq登录的安全验证，不过安装过程和使用过程都有一定的问题，所以我选择了使用浏览器验证，按照下面视频操作即可：
[Polaris][mirai]如果你倒霉遇到了滑块验证_哔哩哔哩_bilibili<https://www.bilibili.com/video/BV1Ka411J7wr/>

Yuki’s

发件人: ***@***.***>
发送时间: 2022年11月24日 20:30
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [murphys7017/polaris-qq-chat-bot] 无法通过滑动验证码 (Issue #3)


登录QQ了，也闪退

―

**Comment by ymy2078069948** [comment]
OK，我试试，辛苦了
